### PR TITLE
Feat/add other model lecture

### PR DESCRIPTION
**Pull request by JonathanRob**
This branch adds several scripts for the in-class activity for the lecture on "Other modeling formalisms".

### CODE REVIEW

**Comment by JonathanRob** [comment]
Minor note: I tried to remove the annoying `^M` characters that Windows added to the end of some lines, but was unsuccessful. These don't affect the code at all though, so they're not really a concern.

**Comment by IVANDOMENZAIN** [comment]
Hi @JonathanRob, the pull request looks good. I have given you admin rights so you can merge it to master when you feel that this is ready. It would be good if you share the latest snapshot of your code in `master` with the students as we would like to keep any other branches just for development purposes and we don't want them to get confused with different code versions. Good luck with your lecture!

**Comment by JonathanRob** [comment]
@IVANDOMENZAIN Ok great, thanks for taking a look. I will be sure to point them to the version on master once I merge it.

**Comment by edkerk** [comment]
> Minor note: I tried to remove the annoying `^M` characters that Windows added to the end of some lines, but was unsuccessful. These don't affect the code at all though, so they're not really a concern.

@JonathanRob: `dos2unix` is often distributed with Unix, there also seems to be a Windows version: https://sourceforge.net/projects/dos2unix/

**Comment by JonathanRob** [comment]
@edkerk Ahh, thank you! I was able to fix it using this package.

**Pull request merged**
